"""add check_in_time and check_out_time to bookings table

Revision ID: 41534446f7ee
Revises: 42f4458b21d8
Create Date: 2025-08-19 10:52:23.759003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41534446f7ee'
down_revision = '42f4458b21d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('check_out_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('check_out_time')
        batch_op.drop_column('check_in_time')

    # ### end Alembic commands ###
