"""Add attachment_file to payments

Revision ID: 7f0357e763a2
Revises: b43a92faae3a
Create Date: 2025-08-02 11:42:22.027032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f0357e763a2'
down_revision = 'b43a92faae3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('attachment_file')

    # ### end Alembic commands ###
